In [29]:
import pandas as pd
import numpy as np

df = pd.read_csv("gestão_funcionarios.csv")

#Mostrar o DataFrame antes das alterações
display(df)

#Aumento de 10% do Salario
df["Salario"] = round((df["Salario"] * 1.1), 2)

#Calcular Salario Anual
df["Salario Anual"] = df["Salario"] * 12

#Guardar Alterações no ficheiro CSV
df.to_csv("gestão_funcionarios.csv", index=False)

#Mostrar Maior Salário
maior_salario = df.loc[df["Salario"].idxmax()] # => Serve para dizer o indice do Salario mais alto ou valor mais alto
print(f"O funcionário com o maior salário é {maior_salario["Nome"]} com {maior_salario["Salario"]}€, e Salário Anual de {maior_salario["Salario Anual"]}€")

#Depois das alterações
display(df)

     Nome  Salario  Salario Anual
0  Carlos   1200.0        14400.0
1   Maria   1500.0        18000.0
2   Joana   1000.0        12000.0

O funcionário com o maior salário é Maria com 1650.0€, e Salário Anual de 19800.0€

     Nome  Salario  Salario Anual
0  Carlos   1320.0        15840.0
1   Maria   1650.0        19800.0
2   Joana   1100.0        13200.0